// <auto-generated />
using Anubis.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Anubis.Migrations
{
    [DbContext(typeof(AnubisContext))]
    [Migration("20260102192105_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("Anubis.Database.Models.BlacklistedHash", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BlacklistedHashes");
                });

            modelBuilder.Entity("Anubis.Database.Models.Guild", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("LogChannel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("Anubis.Database.Models.HashSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HashId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Punishment")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PunishmentDuration")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("HashId");

                    b.ToTable("HashSettings");
                });

            modelBuilder.Entity("Anubis.Database.Models.HashSetting", b =>
                {
                    b.HasOne("Anubis.Database.Models.Guild", "Guild")
                        .WithMany("Hashes")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Anubis.Database.Models.BlacklistedHash", "Hash")
                        .WithMany()
                        .HasForeignKey("HashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("Hash");
                });

            modelBuilder.Entity("Anubis.Database.Models.Guild", b =>
                {
                    b.Navigation("Hashes");
                });
#pragma warning restore 612, 618
        }
    }
}
